// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5l7aq0arMklmYmRCrP-FTukcuAn8lA9o',
    appId: '1:629501785872:web:1cdd6278c09d955cc6d795',
    messagingSenderId: '629501785872',
    projectId: 'hackathum24mun-67',
    authDomain: 'hackathum24mun-67.firebaseapp.com',
    storageBucket: 'hackathum24mun-67.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUTK4WrIEDBUFn3XB2Iti-iC2W-9uZowQ',
    appId: '1:629501785872:android:f741644c92e37c39c6d795',
    messagingSenderId: '629501785872',
    projectId: 'hackathum24mun-67',
    storageBucket: 'hackathum24mun-67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE9b_GIQeSJS3R-e6VzlXS1f4SBruD0OQ',
    appId: '1:629501785872:ios:f4c0af0e870d55b2c6d795',
    messagingSenderId: '629501785872',
    projectId: 'hackathum24mun-67',
    storageBucket: 'hackathum24mun-67.firebasestorage.app',
    iosBundleId: 'com.example.synkronizeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE9b_GIQeSJS3R-e6VzlXS1f4SBruD0OQ',
    appId: '1:629501785872:ios:f4c0af0e870d55b2c6d795',
    messagingSenderId: '629501785872',
    projectId: 'hackathum24mun-67',
    storageBucket: 'hackathum24mun-67.firebasestorage.app',
    iosBundleId: 'com.example.synkronizeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5l7aq0arMklmYmRCrP-FTukcuAn8lA9o',
    appId: '1:629501785872:web:eb9c5905b46f6743c6d795',
    messagingSenderId: '629501785872',
    projectId: 'hackathum24mun-67',
    authDomain: 'hackathum24mun-67.firebaseapp.com',
    storageBucket: 'hackathum24mun-67.firebasestorage.app',
  );

}